package salmon.community.model;

public class Soup {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SOUP.ID
     *
     * @mbg.generated Fri Sep 10 16:07:34 CST 2021
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SOUP.GMT_UPDATE
     *
     * @mbg.generated Fri Sep 10 16:07:34 CST 2021
     */
    private Long gmtUpdate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SOUP.CONTENT
     *
     * @mbg.generated Fri Sep 10 16:07:34 CST 2021
     */
    private String content;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SOUP.ID
     *
     * @return the value of SOUP.ID
     *
     * @mbg.generated Fri Sep 10 16:07:34 CST 2021
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SOUP.ID
     *
     * @param id the value for SOUP.ID
     *
     * @mbg.generated Fri Sep 10 16:07:34 CST 2021
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SOUP.GMT_UPDATE
     *
     * @return the value of SOUP.GMT_UPDATE
     *
     * @mbg.generated Fri Sep 10 16:07:34 CST 2021
     */
    public Long getGmtUpdate() {
        return gmtUpdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SOUP.GMT_UPDATE
     *
     * @param gmtUpdate the value for SOUP.GMT_UPDATE
     *
     * @mbg.generated Fri Sep 10 16:07:34 CST 2021
     */
    public void setGmtUpdate(Long gmtUpdate) {
        this.gmtUpdate = gmtUpdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SOUP.CONTENT
     *
     * @return the value of SOUP.CONTENT
     *
     * @mbg.generated Fri Sep 10 16:07:34 CST 2021
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SOUP.CONTENT
     *
     * @param content the value for SOUP.CONTENT
     *
     * @mbg.generated Fri Sep 10 16:07:34 CST 2021
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }
}